INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (1, 'Product 1', 10);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (2, 'Product 2', 20);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (3, 'Product 3', 30);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (4, 'Product 4', 40);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (5, 'Product 5', 50);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (6, 'Product 6', 110);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (7, 'Product 7', 210);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (8, 'Product 8', 310);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (9, 'Product 9', 410);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (10, 'Product 10', 150);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (11, 'Product 11', 110);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (12, 'Product 12', 120);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (13, 'Product 13', 310);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (14, 'Product 14', 140);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (15, 'Product 15', 150);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (16, 'Product 16', 110);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (17, 'Product 17', 120);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (18, 'Product 18', 130);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (19, 'Product 19', 140);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (20, 'Product 20', 250);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (21, 'Product 21', 210);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (22, 'Product 22', 220);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (23, 'Product 23', 230);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (24, 'Product 24', 240);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (25, 'Product 25', 250);



INSERT INTO USERS (ID, NAME)
VALUES (1, 'USER 1');
INSERT INTO USERS (ID, NAME)
VALUES (2, 'USER 2');
INSERT INTO USERS (ID, NAME)
VALUES (3, 'USER 3');
INSERT INTO USERS (ID, NAME)
VALUES (4, 'USER 4');
INSERT INTO USERS (ID, NAME)
VALUES (5, 'USER 5');


INSERT INTO USERS_PRODUCT (ID, USER_ID, PRODUCT_ID, PRICE, COUNT)
VALUES (1, 1, 2, 20, 1);
INSERT INTO USERS_PRODUCT (ID, USER_ID, PRODUCT_ID, PRICE, COUNT)
VALUES (2, 2, 2, 20, 2);
INSERT INTO USERS_PRODUCT (ID, USER_ID, PRODUCT_ID, PRICE, COUNT)
VALUES (3, 3, 3, 30, 3);
INSERT INTO USERS_PRODUCT (ID, USER_ID, PRODUCT_ID, PRICE, COUNT)
VALUES (4, 4, 4, 40, 4);

