INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (1, 'Product 1', 10);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (2, 'Product 2', 20);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (3, 'Product 3', 30);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (4, 'Product 4', 40);
INSERT INTO PRODUCT (ID, NAME, PRICE)
VALUES (5, 'Product 5', 50);


INSERT INTO USERS (ID, NAME)
VALUES (1, 'USER 1');
INSERT INTO USERS (ID, NAME)
VALUES (2, 'USER 2');
INSERT INTO USERS (ID, NAME)
VALUES (3, 'USER 3');
INSERT INTO USERS (ID, NAME)
VALUES (4, 'USER 4');
INSERT INTO USERS (ID, NAME)
VALUES (5, 'USER 5');


INSERT INTO USERS_PRODUCT (ID, USER_ID, PRODUCT_ID, PRICE, COUNT)
VALUES (1, 1, 2, 20, 1);
INSERT INTO USERS_PRODUCT (ID, USER_ID, PRODUCT_ID, PRICE, COUNT)
VALUES (2, 2, 2, 20, 2);
INSERT INTO USERS_PRODUCT (ID, USER_ID, PRODUCT_ID, PRICE, COUNT)
VALUES (3, 3, 3, 30, 3);
INSERT INTO USERS_PRODUCT (ID, USER_ID, PRODUCT_ID, PRICE, COUNT)
VALUES (4, 4, 4, 40, 4);

